#! /bin/zsh
# Joust Test Suite		-*- mode:zsh -*-
# Copyright (C) 2020 Nathan Sidwell, nathan@acm.org
# License: Affero GPL v3.0

pushd ${0%/*}
setopt nullglob
for subdir in **(/) ; do
    echo ${subdir}/*(.^*)
done
popd
