#! zsh
# Joust Test Suite		-*- mode:zsh -*-
# Copyright (C) 2020 Nathan Sidwell, nathan@acm.org
# Not For Distribution

. $JOUST

pushd $srcdir
setopt nullglob
for subdir in $@ ; do
    echo $subdir/*(.^*)
done
popd
